version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  test:

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:1.1.8
    container_name: explorerdb.mynetwork.com
    hostname: explorerdb.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test

  explorer.mynetwork.com:
    image: hyperledger/explorer:1.1.8
    container_name: explorer.mynetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./fabric-explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ../organizations/peerOrganizations/genh.example.com/tlsca/tlsca.genh.example.com-cert.pem:/var/hyperledger/pki/genh/tlsca/cert.pem
      - ../organizations/peerOrganizations/genh.example.com/users/Admin@genh.example.com/msp/signcerts/cert.pem:/var/hyperledger/pki/genh/admin/signcerts/cert.pem
      - ../organizations/peerOrganizations/genh.example.com/users/Admin@genh.example.com/msp/keystore/key.key:/var/hyperledger/pki/genh/admin/keystore/key.key
      - ../organizations/peerOrganizations/genh.example.com/connection-genh-explorer.json:/var/hyperledger/network/genh/connection.json
      - walletstore:/opt/explorer/wallet
    # ports:
    #   - 8080:8080
    depends_on:
      explorerdb.mynetwork.com:
        condition: service_healthy
    networks:
      - test